# .goreleaser.yml
project_name: apigeecli

builds:
  -
    main: ./main.go
    binary: apigeecli
    goos:
      - linux
      - darwin
      - windows
    ldflags:
    - -s -w -X main.Version={{.Commit}}
archive:
  name_template: "{{ .ProjectName }}_{{.Tag}}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  wrap_in_directory: true  
  format_overrides:
  - goos: windows
    format: zip
release:
  draft: true
  prerelease: true
nfpm:
  name_template: "{{ .ProjectName }}_{{.Tag}}_{{ .Os }}_{{ .Arch }}"
  bindir: bin