sudo: required
dist: trusty
language: go

env:
  global: 
    - GOX_FLAGS="-arch amd64"

go_import_path: github.com/srinandan/apigeecli

go:
  - 1.12.x
  
install: true

notifications:
  email: false

script:
  - env GO111MODULE=on go build -o apigeecli
  - env GO111MODULE=on go test -v ./...
