dist: xenial
language: go
env:
  - GO111MODULE=on GOFLAGS='-mod vendor'
go:
  - 1.12.x
git:
  depth: 1
install: true
notifications:
  email: false

script:
  - go build -o apigeecli -ldflags "-w -s -X cmd/cmd.GitVersion=test"
  - go test -v -race
