sudo: required
dist: trusty
language: go

env:
  global: 
    - GOX_FLAGS="-arch amd64"
    - TRAVIS_GO_VERSION=$(cat .go-version) 

go_import_path: github.com/srinandan/apigeecli

go:
  - 1.12.x

install: true

notifications:
  email: false

script:
  - go build -o apigeecli -ldflags "-w -s -X cmd/cmd.GitVersion=test"
  - go test -v -race